version: '3.8'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - gymnetwork

  backend:
    build:
      context: $BACKEND_ROOT
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - ${BACKEND_BIND}:${BACKEND_BIND}
    depends_on:
      - postgres
    volumes:
      - "./static:/app/static"
      - type: bind
        source: $BACKEND_ROOT/src
        target: /app/src
        consistency: delegated
    environment:
      - TSC_WATCHFILE=UseFsEvents
      - NODE_ENV=development
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - gymnetwork

networks:
  gymnetwork:

volumes:
  postgres-data: